### ISSUE TITLE
Bhat ≠ Thai Baht

### ISSUE THREAD

**Issue by Jay1** [farhan2077/symbol-search#2]
Hey guys,

I believe there is a small typo on the web page here 

![image](https://user-images.githubusercontent.com/1072434/119426674-a2c8ef00-bcd7-11eb-9330-847d69116f18.png)

I'm fairly sure it should be Baht https://en.wikipedia.org/wiki/Thai_baht

**Comment by farhan2077** [comment]
Thanks @Jay1 for mentioning this. Fixed now.
